"""Hierarchical document chunker using Docling.

Produces two levels of chunks per document section:
  - section: the full section text (parent), used for context retrieval
  - chunk: sub-sections of the section text (children), used for similarity search

Context summaries are generated by Claude for each child chunk and prepended
to the chunk content before embedding (contextual retrieval pattern).
"""
from __future__ import annotations

import asyncio
from pathlib import Path

import anthropic
from pydantic import BaseModel


class HierarchicalChunk(BaseModel):
    content: str
    context_summary: str         # empty string for section-level chunks
    chunk_level: str             # 'section' or 'chunk'
    parent_position: int | None  # index in the flat list of the parent section; None if IS a section


class _ContextSummaryOutput(BaseModel):
    summary: str


_CONTEXT_SUMMARY_SYSTEM = """\
You are a document indexing assistant. Given a document section and a specific chunk
extracted from that section, write a single sentence describing what the chunk covers
and where it sits in the document. This sentence will be prepended to the chunk before
embedding for semantic search. Be specific and concise — one sentence only.\
"""


async def _generate_context_summary(
    client: anthropic.AsyncAnthropic,
    section_content: str,
    chunk_content: str,
    settings,
) -> str:
    user_content = (
        f"Document section:\n{section_content[:2000]}\n\n"
        f"Chunk to summarize:\n{chunk_content}"
    )
    response = await client.messages.create(
        model=settings.claude_model,
        max_tokens=128,
        system=_CONTEXT_SUMMARY_SYSTEM,
        messages=[{"role": "user", "content": user_content}],
        tools=[
            {
                "name": "output_summary",
                "description": "Output the one-sentence context summary.",
                "input_schema": _ContextSummaryOutput.model_json_schema(),
            }
        ],
        tool_choice={"type": "tool", "name": "output_summary"},
    )
    tool_block = next(b for b in response.content if b.type == "tool_use")
    return _ContextSummaryOutput.model_validate(tool_block.input).summary


def _split_into_child_texts(text: str, max_chars: int) -> list[str]:
    """Split text at paragraph boundaries so each piece is under max_chars."""
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    if not paragraphs:
        return [text] if text.strip() else []

    chunks: list[str] = []
    current: list[str] = []
    current_len = 0

    for para in paragraphs:
        if current and current_len + len(para) + 2 > max_chars:
            chunks.append("\n\n".join(current))
            current = [para]
            current_len = len(para)
        else:
            current.append(para)
            current_len += len(para) + 2

    if current:
        chunks.append("\n\n".join(current))

    return chunks


def _is_heading(item) -> bool:
    label = getattr(item, "label", None)
    if label is None:
        return False
    label_str = str(label).lower()
    return any(kw in label_str for kw in ("section_header", "heading", "title"))


async def chunk_document(
    path: Path,
    client: anthropic.AsyncAnthropic,
    settings,
) -> list[HierarchicalChunk]:
    """Parse a document with Docling and return a flat list of HierarchicalChunk objects.

    Layout: for each section, the section chunk comes first immediately followed by its
    child chunks. parent_position on a child is the index of its section chunk in the list.
    """
    from docling.document_converter import DocumentConverter

    loop = asyncio.get_event_loop()
    converter = DocumentConverter()
    result = await loop.run_in_executor(None, converter.convert, str(path))
    doc = result.document

    # --- Group document items into (title, body) pairs ---
    sections: list[tuple[str, str]] = []
    current_title = "Document"
    current_body: list[str] = []

    for item, _level in doc.iterate_items():
        text = getattr(item, "text", None) or ""
        if not text.strip():
            continue
        if _is_heading(item):
            if current_body:
                sections.append((current_title, "\n\n".join(current_body)))
            current_title = text.strip()
            current_body = []
        else:
            current_body.append(text.strip())

    if current_body:
        sections.append((current_title, "\n\n".join(current_body)))

    # Fall back to full export if Docling found no structure
    if not sections:
        full_text = doc.export_to_markdown()
        sections = [("Document", full_text)]

    parent_max_chars = settings.parent_chunk_size * 4  # ~4 chars per token
    child_max_chars = settings.chunk_size * 4

    # --- Build chunks section by section ---
    flat: list[HierarchicalChunk] = []
    semaphore = asyncio.Semaphore(5)

    for title, body in sections:
        section_content = f"{title}\n\n{body}"
        section_position = len(flat)

        flat.append(
            HierarchicalChunk(
                content=section_content[:parent_max_chars],
                context_summary="",
                chunk_level="section",
                parent_position=None,
            )
        )

        child_texts = _split_into_child_texts(body, child_max_chars) or [body]

        async def make_child(child_text: str, sec_pos: int = section_position, sec_content: str = section_content) -> HierarchicalChunk:
            async with semaphore:
                summary = await _generate_context_summary(
                    client, sec_content, child_text, settings
                )
            return HierarchicalChunk(
                content=child_text,
                context_summary=summary,
                chunk_level="chunk",
                parent_position=sec_pos,
            )

        child_chunks = await asyncio.gather(*[make_child(ct) for ct in child_texts])
        flat.extend(child_chunks)

    return flat
